# This is a basic workflow to help you get started with Actions

name: generation-stage

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'version string '
        required: true
        default: 'IFC4.3.RC'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-schema:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Create generation branch
        run: |
          echo "Creating generation branch with version ${{ github.event.inputs.version }}"
          echo git checkout -b "generation/${{ github.event.inputs.version }}"
      - name: Run schema generation
        run: |
          echo 'Workspace directory is ${{ github.workspace }}'
          echo 'Home directory is $HOME'
          & "${{ github.workspace }}\build\IfcDocLite.exe" "${{ github.workspace }}\IFC4x3" -FS "${{ github.workspace }}\output"
      - name: Upload schema
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.version }}
          path: ${{ github.workspace }}\output
